=== Nelson198/DWeb2019/TP2/pr.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT projeto (designação, cabeçalho, grupo, descrição, documentos, data)>
<!ELEMENT designação (#PCDATA)>
<!ELEMENT cabeçalho (chave, título, subtítulo, data-início, data-fim, professor)>
<!ELEMENT chave (#PCDATA)>
<!ELEMENT título (#PCDATA)>
<!ELEMENT subtítulo (#PCDATA)>
<!ELEMENT data-início (#PCDATA)>
<!ELEMENT data-fim (#PCDATA)>
<!ELEMENT professor (#PCDATA)>
<!ELEMENT grupo (elemento+)>
<!ELEMENT elemento (nome, email, github)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT github (#PCDATA)>
<!ELEMENT descrição (#PCDATA|ficheiro)*>
<!ELEMENT ficheiro (#PCDATA)>
<!ELEMENT documentos (documento+)>
<!ELEMENT documento (#PCDATA)>
<!ELEMENT data (#PCDATA)>

<!ATTLIST professor 
          webpage CDATA #REQUIRED
          email CDATA #REQUIRED>
<!ATTLIST email
          link CDATA #REQUIRED>
<!ATTLIST github
          link CDATA #REQUIRED>
<!ATTLIST documento
          id CDATA #REQUIRED
          link CDATA #REQUIRED>
<!ATTLIST ficheiro
          id CDATA #REQUIRED>

=== Nelson198/DWeb2019/TP2/pr.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE projeto SYSTEM "PR.dtd">
<projeto>
    <designação>Desenvolvimento de Aplicações WEB (DAW) - Trabalho Prático nº2</designação>
    <cabeçalho>
        <chave>TP2</chave>
        <título>Exploração e compreensão de conceitos associados à linguagem XML: XPATH e DTD's</título>
        <subtítulo>XML - Linguagem de anotação</subtítulo>
        <data-início>24/09/2019</data-início>
        <data-fim>01/10/2019</data-fim>
        <professor webpage="http://www4.di.uminho.pt/~jcr/" email="jcr@di.uminho.pt">José Carlos Ramalho</professor>
    </cabeçalho>
    <grupo>
        <elemento>
            <nome>Nelson José Dias Teixeira</nome>
            <email link="pg41091@alunos.uminho.pt">pg41091@alunos.uminho.pt</email>
            <github link="https://github.com/Nelson198">Nelson198</github>
        </elemento>
    </grupo>
    <descrição>
        No segundo trabalho prático desta U.C. era requirido a realização de alguns exercícios, entre os quais se destacam:
        --> elaborar um <ficheiro id="PR-xml">documento</ficheiro> XML que representasse corretamente a estrutura de uma determinada página WEB; 
        --> definir um <ficheiro id="PR-dtd">DTD</ficheiro> que validasse o presente <ficheiro id="PR-xml">documento</ficheiro>;
        --> resolver os exercícios <ficheiro id="arq-txt">6</ficheiro> e <ficheiro id="arq-dtd">7</ficheiro> da ficha nº3 que foi disponibilizada pelo professor:
            --> quanto ao exercício 6 era necessário escrever algumas expressões XPath para filtrar vários elementos de um dado <ficheiro id="arq-xml">documento</ficheiro> XML.
            --> relativamente ao exercício 7 era pedido a definição de um DTD que validasse o ficheiro mencionado anteriormente.
    </descrição>
    <documentos>
        <documento id="PR-xml" link="PR.xml">Documento atual</documento>
        <documento id="PR-dtd" link="PR.dtd">Ficheiro DTD que valida o projeto (ou seja, este mesmo documento, "PR.xml")</documento>
        <documento id="arq-txt" link="arq.txt">Ficheiro de texto que contém as respostas (e parte do enunciado) do exercício 6 da ficha nº3</documento>
        <documento id="arq-dtd" link="arq.dtd">Ficheiro DTD que valida o documento arq.xml (exercício 7 da ficha nº3)</documento>
        <documento id="arq-xml" link="arq.xml">Ficheiro XML necessário para a realização do exercício 6 e 7 da ficha nº3</documento>
    </documentos>
    <data>
        27/09/2019
    </data>
</projeto>
